### PR TITLE
Typo "Amendemnt" fix

### PR DESCRIPTION
**Pull request by waterhouse**

### CODE REVIEW

**Comment by itsJoKr** [comment]
The way this is set up, you would basically change the constitution with this PR. So you need to have the approval of both houses.

**Comment by criloz** [comment]
or accumulate all those small fixes and wait until a new amendment comes.

**Comment by shaleh** [comment]
The author could use git history editing tools to "time travel".

**Comment by JesseKPhillips** [comment]
This is fixed in the rewrite/history branch

**Pull request closed without merging**
